/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TP1;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.Timer;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author someone
 */
public class TP1UI extends javax.swing.JFrame {

    /**
     * Creates new form TP1UI
     */
    public TP1UI() {
        initComponents();
        jTextPane1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFrame1 = new javax.swing.JFrame();
        jLabelMemorySize = new javax.swing.JLabel();
        jTextFieldMemorySize = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButtonPlayPause = new javax.swing.JButton();
        jButtonRewind = new javax.swing.JButton();
        jButtonForward = new javax.swing.JButton();
        jLabelAC = new javax.swing.JLabel();
        jTextFieldAC = new javax.swing.JTextField();
        jLabelAX = new javax.swing.JLabel();
        jTextFieldAX = new javax.swing.JTextField();
        jLabelBX = new javax.swing.JLabel();
        jTextFieldBX = new javax.swing.JTextField();
        jLabelCX = new javax.swing.JLabel();
        jTextFieldCX = new javax.swing.JTextField();
        jLabelDX = new javax.swing.JLabel();
        jTextFieldDX = new javax.swing.JTextField();
        jLabelRegister = new javax.swing.JLabel();
        jLabelIR = new javax.swing.JLabel();
        jTextFieldIR = new javax.swing.JTextField();
        jLabelPC = new javax.swing.JLabel();
        jTextFieldPC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMemory = new javax.swing.JList<>();
        jLabelMemory = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemOpenFile = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItemConfig = new javax.swing.JMenuItem();

        jFileChooser1.setFileFilter(new ASMFilter());

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame1.setTitle("Config Settings");
        jFrame1.setResizable(false);
        jFrame1.setSize(new java.awt.Dimension(600, 400));

        jLabelMemorySize.setText("Memory Size");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addContainerGap(522, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabelMemorySize)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldMemorySize, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMemorySize)
                    .addComponent(jTextFieldMemorySize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(jTextPane1);

        jButtonPlayPause.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jButtonPlayPause.setIcon(new javax.swing.ImageIcon("/home/someone/Downloads/play-pause(3).png")); // NOI18N
        jButtonPlayPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayPauseActionPerformed(evt);
            }
        });

        jButtonRewind.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jButtonRewind.setIcon(new javax.swing.ImageIcon("/home/someone/Downloads/rewind.png")); // NOI18N

        jButtonForward.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jButtonForward.setIcon(new javax.swing.ImageIcon("/home/someone/Downloads/forward.png")); // NOI18N

        jLabelAC.setText("AC");

        jLabelAX.setText("AX");

        jLabelBX.setText("BX");

        jLabelCX.setText("CX");

        jLabelDX.setText("DX");

        jLabelRegister.setText("Registers");

        jLabelIR.setText("IR");

        jLabelPC.setText("PC");

        jScrollPane1.setViewportView(jListMemory);

        jLabelMemory.setText("Memory");

        jMenu3.setText("File");

        jMenuItemOpenFile.setText("Open File");
        jMenuItemOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenFileActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemOpenFile);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");

        jMenuItemConfig.setText("Config");
        jMenuItemConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConfigActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemConfig);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRegister)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelAX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelBX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelDX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelIR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelMemory)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRewind)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPlayPause)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonForward)
                        .addGap(211, 211, 211))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelRegister)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelPC)
                                .addComponent(jTextFieldPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelAC)
                                .addComponent(jTextFieldAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelAX)
                                .addComponent(jTextFieldAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelBX)
                                .addComponent(jTextFieldBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelCX)
                                .addComponent(jTextFieldCX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelDX)
                                .addComponent(jTextFieldDX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelIR)
                                .addComponent(jTextFieldIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMemory)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonForward, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonPlayPause, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonRewind, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenFileActionPerformed
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            asmFile = jFileChooser1.getSelectedFile();
            AssemblerLoader loader = new AssemblerLoader();
            try {
                this.memory = new Memory(this.memorySize);
                this.cpu = new CPU();
                this.rowCounter = -1;
                this.clearDisplays();
                
                List<Expression> list = loader.loadFile(asmFile.getAbsolutePath());
                DefaultListModel<String> listModel = new DefaultListModel<>();
                    
                loadDisplay(list);
                //System.out.println(this.memory.getInstruction(1));
                loadMemory(list);
                //System.out.println(this.memory.getInstruction(1));
                listModel.addAll(memory.getMemoryArray());
                jListMemory.setModel( listModel );
                
                ActionListener aL = new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {
                        if (cpu.peekInstruction(memory) != null) {
                            cpu.execute(cpu.fetchInstruction(memory));
                            //System.out.println("AC: "+cpu.ac()+" AX: "+cpu.ax()+" BX: "+cpu.bx()+" CX: "+cpu.cx()+" DX: "+cpu.dx());
                            
                            rowCounter += 1;
                            clearDisplays();
                            loadDisplay(list);
                            jTextFieldAC.setText(String.valueOf(cpu.ac()));
                            jTextFieldAX.setText(String.valueOf(cpu.ax()));
                            jTextFieldBX.setText(String.valueOf(cpu.bx()));
                            jTextFieldCX.setText(String.valueOf(cpu.cx()));
                            jTextFieldDX.setText(String.valueOf(cpu.dx()));
                            jTextFieldPC.setText(String.valueOf(cpu.pc()));
                            jTextFieldIR.setText(cpu.ir());
                            
                            DefaultListModel<String> listModel = new DefaultListModel<>();
                            listModel.addAll(memory.getMemoryArray());
                            jListMemory.setModel( listModel );
                        } else {
                            controller.stop();
                        }
                    }
                };
                
                this.controller = new Timer(1000, aL);//create the timer which calls the actionperformed method for every 1000 millisecond(1 second=1000 millisecond)
                this.controller.setRepeats(true);
                    
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(new JFrame(), e.getMessage(), "Dialog",
        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_jMenuItemOpenFileActionPerformed

    private void jMenuItemConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConfigActionPerformed
        jFrame1.setVisible(true);
        jTextFieldMemorySize.setText(String.valueOf(memorySize));
    }//GEN-LAST:event_jMenuItemConfigActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        memorySize = Integer.parseInt(jTextFieldMemorySize.getText());
        System.out.println(String.valueOf(memorySize));
        jFrame1.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonPlayPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayPauseActionPerformed
        if (asmFile == null) {
            JOptionPane.showMessageDialog(new JFrame(), "Load a file first.", "Dialog",
        JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (this.simulationState == null || this.simulationState == "Paused") {
            this.simulationState = "Active";
            this.controller.start();
        } else {
            this.simulationState = "Paused";
            this.controller.stop();
        }
    }//GEN-LAST:event_jButtonPlayPauseActionPerformed
    
    private void loadMemory(List<Expression> instructions) {
        for (int i = 0; i < instructions.size(); i++) {
            this.memory.loadInstruction(null, instructions.get(i).operation, instructions.get(i).operands);
        }
    }
    
    private void clearDisplays() {
        jTextPane1.setText("");
        jTextFieldAC.setText("");
        jTextFieldAX.setText("");
        jTextFieldBX.setText("");
        jTextFieldCX.setText("");
        jTextFieldDX.setText("");
        jTextFieldPC.setText("");
        jTextFieldIR.setText("");
    }
    
    private void loadDisplay(List<Expression> instructions) {
        // Create a custom StyledDocument 
        StyledDocument doc = jTextPane1.getStyledDocument(); 
                
        // Create and set a Style for the text 
        Style bold = doc.addStyle("bold", null); 
        StyleConstants.setForeground(bold, Color.BLACK); 
        StyleConstants.setBold(bold, true); 
        
        Style selectBackground = doc.addStyle("selectBackground", null); 
        StyleConstants.setBackground(selectBackground, Color.GREEN);
        StyleConstants.setForeground(selectBackground, Color.BLACK);
        
        Style selectBackgroundBold = doc.addStyle("selectBackgroundBold", null); 
        StyleConstants.setBackground(selectBackgroundBold, Color.GREEN);
        StyleConstants.setForeground(selectBackgroundBold, Color.BLACK);
        StyleConstants.setBold(selectBackgroundBold, true); 
                    
        // Set the StyledDocument 
        jTextPane1.setStyledDocument(doc); 
                    
        for (int i = 0; i < instructions.size(); i++) {
            // Insert text with custom style 
            try { 
                if ( i == rowCounter) {
                    doc.insertString(doc.getLength(), String.valueOf(instructions.get(i).row)+"  ", selectBackground);
                    doc.insertString(doc.getLength(), instructions.get(i).operation, selectBackgroundBold); 

                    switch (instructions.get(i).operation.toUpperCase()) {
                        case "MOV":
                            doc.insertString(doc.getLength(), " "+instructions.get(i).operands[0]+",", selectBackground);
                            doc.insertString(doc.getLength(), " "+instructions.get(i).operands[1]+"\n", selectBackground);
                            break;
                        case "ADD":
                        case "SUB":
                        case "LOAD":
                        case "STORE":
                            doc.insertString(doc.getLength(), " "+instructions.get(i).operands[0]+"\n", selectBackground);
                        default:
                    }
                } else {
                    doc.insertString(doc.getLength(), String.valueOf(instructions.get(i).row)+"  ", null);
                    doc.insertString(doc.getLength(), instructions.get(i).operation, bold); 

                    switch (instructions.get(i).operation.toUpperCase()) {
                        case "MOV":
                            doc.insertString(doc.getLength(), " "+instructions.get(i).operands[0]+",", null);
                            doc.insertString(doc.getLength(), " "+instructions.get(i).operands[1]+"\n", null);
                            break;
                        case "ADD":
                        case "SUB":
                        case "LOAD":
                        case "STORE":
                            doc.insertString(doc.getLength(), " "+instructions.get(i).operands[0]+"\n", null);
                        default:
                    }
                }
            } catch (BadLocationException e) { 
                e.printStackTrace(); 
            } 
        }
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TP1UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TP1UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TP1UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TP1UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TP1UI().setVisible(true);
            }
        });
    }
    
    private File asmFile; 
    private int memorySize = 100;
    private Memory memory;
    private CPU cpu;
    private Timer controller;
    private String simulationState;
    private int rowCounter;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonForward;
    private javax.swing.JButton jButtonPlayPause;
    private javax.swing.JButton jButtonRewind;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabelAC;
    private javax.swing.JLabel jLabelAX;
    private javax.swing.JLabel jLabelBX;
    private javax.swing.JLabel jLabelCX;
    private javax.swing.JLabel jLabelDX;
    private javax.swing.JLabel jLabelIR;
    private javax.swing.JLabel jLabelMemory;
    private javax.swing.JLabel jLabelMemorySize;
    private javax.swing.JLabel jLabelPC;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JList<String> jListMemory;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItemOpenFile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldAC;
    private javax.swing.JTextField jTextFieldAX;
    private javax.swing.JTextField jTextFieldBX;
    private javax.swing.JTextField jTextFieldCX;
    private javax.swing.JTextField jTextFieldDX;
    private javax.swing.JTextField jTextFieldIR;
    private javax.swing.JTextField jTextFieldMemorySize;
    private javax.swing.JTextField jTextFieldPC;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
